---
title: "ClimateR package"
output: html_document
editor_options: 
  chunk_output_type: console
---

From: https://mikejohnson51.github.io/climateR-intro

```{r}
remotes::install_github("mikejohnson51/AOI") # suggested!
remotes::install_github("mikejohnson51/climateR")

library(climateR)
library(AOI)
```

Get grid MET data. http://www.climatologylab.org/gridmet.html

Single variable, one day, one state.
```{r}
param_meta$gridmet

rain <- getGridMET(aoi_get(state = "FL"), 
                   param = "prcp", 
                   startDate = "2020-03-10")

plot(rain$prcp)
plot(aoi_get(state = "FL")$geometry, add = TRUE)

data <- getGridMET(aoi_get(state = "FL"), 
                   param = "fmoist_1000", 
                   startDate = "2020-03-10")

plot(data$fmoist_1000)
plot(aoi_get(state = "FL")$geometry, add = TRUE)
```

Get for ANF boundaries.
```{r}
download.file(url = "https://www.dropbox.com/s/wo52hwy6ol83nt8/NorthFloridaPublicLandHexagons10km.zip?dl=1",
              destfile = "data/TempPubLand.zip")
unzip("data/TempPubLand.zip", exdir = "data")

LandHex.sf <- read_sf(dsn = "data/NorthFloridaPublicLandHexagons10km") %>%
  dplyr::filter(NAME == "APALACHICOLA")

data <- getGridMET(LandHex.sf, 
                   param = "fmoist_1000", 
                   startDate = "2020-03-10")

plot(data$fmoist_1000)
plot(LandHex.sf$geometry, add = TRUE) # not the same CRS
```

Convert to a {stars} object
```{r}
library(stars)
data.st <- st_as_stars(data$fmoist_1000)

data.st
```

Map
```{r}
library(tmap)

tm_shape(data.st) +
  tm_raster() +
tm_shape(LandHex.sf) +
  tm_borders()
```

One variable, 31 days.
```{r}
data <- getGridMET(LandHex.sf, 
                   param = "fmoist_1000", 
                   startDate = "2020-03-01",
                   endDate = "2020-03-31")
data.st <- st_as_stars(data$fmoist_1000)

names(data.st) <- "fmoist_1000"

library(lubridate)

days <- seq(as_date("2020-03-01"), 
            as_date("2020-03-31"), 
            by = "day")

( data.st <- st_set_dimensions(data.st, 
                               which = 3, 
                               values = days, names = "date") )

LandHexLL.sf <- LandHex.sf %>%
  st_transform(crs = st_crs(data.st))

X <- st_crop(data.st, 
             LandHexLL.sf, 
             crop = TRUE)

ggplot() +  
  geom_stars(data = X) + 
  facet_wrap("date") +
  scale_fill_viridis_c() +
  coord_sf() +
  theme_map() +
  theme(legend.position = "bottom") +
  theme(legend.key.width = unit(2, "cm"))
```

Two variables, 31 days.
```{r}
data <- getGridMET(LandHex.sf, 
                   param = c("prcp", "tmax"),
                   startDate = "2019-03-01",
                   endDate = "2019-03-31")

data.st <- st_as_stars(data$prcp)
names(data.st) <- "prcp"

days <- seq(as_date("2020-03-01"), 
            as_date("2020-03-31"), 
            by = "day")

data.st <- st_set_dimensions(data.st, 
                             which = 3, 
                             values = days, names = "date")

( data.st <- data.st %>%
  mutate(tmax = ( as.vector(data$tmax) - 273.16 ) * 9/5 + 32,
         prcp = if_else(prcp < 0, 0, prcp * .03937008)) )

ggplot() +  
  geom_stars(data = data.st[1]) + 
  facet_wrap("date") +
  scale_fill_viridis_c() +
  coord_sf() +
  theme_map() +
  theme(legend.position = "bottom") +
  theme(legend.key.width = unit(2, "cm"))
```

Point based data
```{r}
AOI <- AOI::geocode('Tallahassee, Florida', pt = TRUE)
ts  <- getGridMET(AOI, param = 'tmax', startDate = "2020-01-01", endDate = "2020-11-30")

ggplot(data = ts) + 
  aes(x = date, y = ( tmax - 273.16 ) ) + 
  geom_line() +
  theme_linedraw() + 
  labs(title = "Daily High Temperature: Tallahassee, FL 2020", x = "Date", y = "Temperature (C)")
```

Compute KDBI for each grid point

Start with grid locations (1:30, 1)
```{r}
NetRst <- NULL

for(i in 1:30){

Rainfall24 <- data.st$prcp[i, 1, ]
PR <- lag(Rainfall24)
PR[1] <- 0

CumR <- 0
NetR <- numeric()

for(i in 1:length(Rainfall24)) {
  R24 <- Rainfall24[i]
  if (R24 == 0) {
    NetR[i] <- 0
    CumR <- 0
  } 
  else if(R24 > 0 & R24 <= .2) {
      CumR <- CumR + R24
      if (PR[i] > .2 | CumR > .2) NetR[i] <- R24
      else if (CumR > .2) NetR[i] <- CumR - .2
      else NetR[i] <- 0
    }
  else if (R24 > .2) {
      if (CumR <= .2) {
      NetR[i] <- CumR + R24 - .2
      CumR <- CumR + R24
      }
      else {
      NetR[i] <- R24
      CumR <- CumR + R24
      }
  }
}

NetRst <- c(NetRst, NetR)

}


```
